apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: daprio-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: ghcr.io/dapr/kubernetes-operator-catalog:latest
  displayName: dapr.io catalog
  grpcPodConfig:
    securityContextConfig: restricted
  publisher: dapr.io
  updateStrategy:
    registryPoll:
      interval: 10m
